dist: trusty
sudo: false

language: ruby

rvm:
  - 2.5.7

addons:
  postgresql: "9.6"
  apt:
    update: true
    packages:
      - google-chrome-stable

cache:
  bundler: true
  yarn: true

env:
  global:
    - CC_TEST_REPORTER_ID=4fc8a11662c55757f43db35ae5235374c7e3614adabdf5e3365addc845867081

branches:
  only:
    - master

before_install:
  - gem update --system
  - gem install bundler

  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
  - curl -O https://chromedriver.storage.googleapis.com/2.37/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d chromedriver
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 -o ./cc-test-reporter
  - chmod +x ./cc-test-reporter

  - export PATH="$HOME/.yarn/bin:$PATH:`pwd`/chromedriver"

install:
  - bundle --jobs=3 --retry=3 --deployment --without development production
  - yarn install --frozen-lockfile

before_script:
  - RAILS_ENV=test ./bin/rake assets:precompile
  - ./cc-test-reporter before-build

script: ./bin/rake db:create db:migrate spec

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
