dist: trusty
sudo: false

language: ruby

rvm:
  - 2.4.4

addons:
  postgresql: "9.6"
  apt:
    packages:
      - google-chrome-stable

cache: bundler

bundler_args: --jobs=3 --retry=3 --deployment --without development production

branches:
  only:
    - master

before_install:
  - gem update --system
  - gem install bundler

before_script:
  - curl -O https://chromedriver.storage.googleapis.com/2.37/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d chromedriver
  - export PATH=$PATH:`pwd`/chromedriver

script: bundle exec rake db:create db:migrate spec
